"""empty message

Revision ID: 10669720ea91
Revises: 82be37f75ad1
Create Date: 2025-07-16 16:29:25.008450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10669720ea91'
down_revision = '82be37f75ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_late', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lecturer_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flagged_for_review', sa.Boolean(), nullable=True))
        batch_op.alter_column('answers_json',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('plagiarism_score')
        batch_op.drop_column('flagged_questions_json')
        batch_op.drop_column('score')
        batch_op.drop_column('time_spent_seconds')
        batch_op.drop_column('status')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('time_spent_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('flagged_questions_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('plagiarism_score', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('answers_json',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.drop_column('flagged_for_review')
        batch_op.drop_column('lecturer_comments')
        batch_op.drop_column('grade')
        batch_op.drop_column('is_late')

    # ### end Alembic commands ###
