"""empty message

Revision ID: 4c19219bcee1
Revises: 10669720ea91
Create Date: 2025-07-19 19:51:13.450444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c19219bcee1'
down_revision = '10669720ea91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plagiarism_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time_spent_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('time_spent_seconds')
        batch_op.drop_column('plagiarism_score')

    # ### end Alembic commands ###
