"""Add answers and flagged questions to progress and submission

Revision ID: 5f9660f41c04
Revises: eab9a51628ef
Create Date: 2025-07-16 01:16:05.887839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9660f41c04'
down_revision = 'eab9a51628ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('flagged_questions_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('flagged_questions_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('flagged_questions_json')
        batch_op.drop_column('answers_json')

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_column('flagged_questions_json')
        batch_op.drop_column('answers_json')

    # ### end Alembic commands ###
