"""empty message

Revision ID: 97ead45bf4e1
Revises: 4c19219bcee1
Create Date: 2025-07-19 23:36:38.443421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ead45bf4e1'
down_revision = '4c19219bcee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged_questions_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('flagged_questions_json')

    # ### end Alembic commands ###
