"""Add time_spent_seconds to progress and submission, update question fields

Revision ID: b355c991e196
Revises: 5f9660f41c04
Create Date: 2025-07-16 03:52:59.515413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b355c991e196'
down_revision = '5f9660f41c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_user_assessment_uc', ['user_id', 'assessment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_constraint('_user_assessment_uc', type_='unique')
        batch_op.drop_column('time_spent_seconds')

    # ### end Alembic commands ###
