"""ADD ONDELETE CASCADE TO Question.assessment_id

Revision ID: eab9a51628ef
Revises: 3a759e3ca025
Create Date: 2025-05-06 14:18:05.080518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab9a51628ef'
down_revision = '3a759e3ca025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_1', 'assessments', ['assessment_id'], ['id'])

    # ### end Alembic commands ###
